export const carreiraParagens = {
  '12E': [
    'Martim Moniz',
    'Socorro',
    'Largo do Terreirinho',
    'Rua dos Lagares',
    'São Tomé',
    'Largo das Portas do Sol',
    'Santa Luzia',
    'Limoeiro',
    'Sé',
    'Rua da Conceição',
    'Largo Academia Nacional de Belas Artes',
    'Rua Serpa Pinto',
    'Chiado',
    'Praça Luís de Camões'
  ],
  '15E': [
    'Praça da Figueira',
    'Rua da Prata',
    'Praça do Comércio',
    'Corpo Santo',
    'Cais do Sodré',
    'Santos',
    'Conde Barão',
    'Av. 24 de Julho / Cais Rocha Conde Óbidos',
    'Av. 24 de Julho / Museu Nacional de Arte Antiga',
    'Rua Presidente Arriaga',
    'Infante Santo',
    'Rua Garcia de Orta',
    'Calçada das Necessidades',
    'Largo das Necessidades',
    'Rua da Junqueira / Museu dos Coches',
    'Rua da Junqueira / Cordoaria Nacional',
    'Calvário',
    'Santo Amaro',
    'Avenida da Índia / Belém',
    'Mosteiro dos Jerónimos',
    'Centro Cultural de Belém',
    'Largo da Princesa',
    'Avenida da Índia / Pedrouços',
    'Dafundo',
    'Algés Mercado',
    'Algés Estação',
    'Algés (Jardim)'
  ],
  '18E': [
    'Cais do Sodré',
    'Corpo Santo',
    'Santos',
    'Conde Barão',
    'Av. 24 de Julho / Cais Rocha Conde Óbidos',
    'Av. 24 de Julho / Museu Nacional de Arte Antiga',
    'Rua Presidente Arriaga',
    'Infante Santo',
    'Rua Garcia de Orta',
    'Rua Domingos Sequeira',
    'Largo da Boa-Hora',
    'Rua da Junqueira / Boa-Hora',
    'Calçada da Ajuda',
    'Palácio Nacional da Ajuda',
    'Rua do Cruzeiro',
    'Estrada dos Arneiros',
    'Calçada do Mirante',
    'Cemitério da Ajuda'
  ],
  '24E': [
    'Campolide (Praça da Artilharia Um)',
    'Rua de Campolide / Rua Marquês da Fronteira',
    'Amoreiras',
    'Rua Joaquim António de Aguiar',
    'Largo do Rato',
    'Rua da Escola Politécnica',
    'Praça do Príncipe Real',
    'São Pedro de Alcântara',
    'Chiado',
    'Rua Serpa Pinto',
    'Praça Luís de Camões'
  ],
  '25E': [
    'Campo de Ourique (Prazeres)',
    'Prazeres',
    'Rua Saraiva de Carvalho',
    'Basílica da Estrela',
    'Largo da Estrela',
    'Assembleia da República',
    'São Bento',
    'Calçada do Combro',
    'Largo do Chiado',
    'Chiado',
    'Rua Serpa Pinto',
    'Rua do Alecrim',
    'Corpo Santo',
    'Rua da Alfândega',
    'Casa dos Bicos',
    'Campo das Cebolas'
  ],
  '28E': [
    'Martim Moniz',
    'Socorro',
    'Largo do Terreirinho',
    'Rua dos Lagares',
    'São Tomé',
    'Largo das Portas do Sol',
    'Santa Luzia',
    'Limoeiro',
    'Sé',
    'Rua da Conceição',
    'Chiado',
    'Praça Luís de Camões',
    'Calhariz (Bica)',
    'Santa Catarina',
    'Assembleia da República',
    'São Bento',
    'Estrela',
    'Basílica da Estrela',
    'Rua Saraiva de Carvalho',
    'Campo de Ourique (Igreja)',
    'Campo de Ourique (Mercado)',
    'Campo de Ourique (Prazeres)'
  ]
};